services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: flats
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  spider:
    build: spider
    depends_on:
      db:
        condition: service_healthy
  web:
    build: web
    ports:
      - 8080:5000
    depends_on:
      spider:
        condition: service_completed_successfully
